defmodule Identity do
  @moduledoc """
  Generated by erl2ex (http://github.com/dazuma/erl2ex)
  From Erlang source: (Unknown source file)
  At: 2019-12-20 13:57:24

  """

  def main() do
    {:ok, context} = :erlzmq.context()
    {:ok, sink} = :erlzmq.socket(context, :router)
    :ok = :erlzmq.bind(sink, 'inproc://example')
    {:ok, anonymous} = :erlzmq.socket(context, :req)
    :ok = :erlzmq.connect(anonymous, 'inproc://example')
    :ok = :erlzmq.send(anonymous, "ROUTER uses a generated 5 byte identity")
    #:erlzmq_util.dump(sink)
    IO.inspect(sink, label: "1. sink")
    {:ok, identified} = :erlzmq.socket(context, :req)
    :ok = :erlzmq.setsockopt(identified, :identity, "PEER2")
    :ok = :erlzmq.connect(identified, 'inproc://example')
    :ok = :erlzmq.send(identified, "ROUTER socket uses REQ's socket identity")
    #:erlzmq_util.dump(sink)
    IO.inspect(sink, label: "2. sink")
    :erlzmq.close(sink)
    :erlzmq.close(anonymous)
    :erlzmq.close(identified)
    :erlzmq.term(context)
  end

end

Identity.main
