defmodule msgqueue do
  @moduledoc """
  Generated by erl2ex (http://github.com/dazuma/erl2ex)
  From Erlang source: (Unknown source file)
  At: 2019-12-20 13:57:26

  """

  def main(_) do
    {:ok, context} = :erlzmq.context()
    {:ok, frontend} = :erlzmq.socket(context, [:router, {:active, true}])
    :ok = :erlzmq.bind(frontend, 'tcp://*:5559')
    {:ok, backend} = :erlzmq.socket(context, [:dealer, {:active, true}])
    :ok = :erlzmq.bind(backend, 'tcp://*:5560')
    :erlzmq_device.queue(frontend, backend)
    :ok = :erlzmq.close(frontend)
    :ok = :erlzmq.close(backend)
    :ok = :erlzmq.term(context)
  end

end
