defmodule Psenvpub do
  @moduledoc """
  Generated by erl2ex (http://github.com/dazuma/erl2ex)
  From Erlang source: (Unknown source file)
  At: 2019-12-20 13:57:29

  """

  def main() do
    {:ok, context} = :erlzmq.context()
    {:ok, publisher} = :erlzmq.socket(context, :pub)
    :ok = :erlzmq.bind(publisher, 'tcp://*:5563')
    loop(publisher)
    :ok = :erlzmq.close(publisher)
    :ok = :erlzmq.term(context)
  end


  def loop(publisher) do
    :ok = :erlzmq.send(publisher, "A", [:sndmore])
    :ok = :erlzmq.send(publisher, "We don't want to see this")
    :ok = :erlzmq.send(publisher, "B", [:sndmore])
    :ok = :erlzmq.send(publisher, "We would like to see this")
    :timer.sleep(1000)
    loop(publisher)
  end

end

Psenvpub.main
