defmodule Rrworker do
  @moduledoc """
  Generated by erl2ex (http://github.com/dazuma/erl2ex)
  From Erlang source: (Unknown source file)
  At: 2019-12-20 13:57:32

  """

  def main() do
    {:ok, context} = :erlzmq.context()
    {:ok, responder} = :erlzmq.socket(context, :rep)
    #:ok = :erlzmq.connect(responder, 'tcp://*:5560')
    :ok = :erlzmq.connect(responder, 'tcp://localhost:5560')
    loop(responder)
    :ok = :erlzmq.close(responder)
    :ok = :erlzmq.term(context)
  end


  def loop(socket) do
    {:ok, req} = :erlzmq.recv(socket)
    :io.format('Received request: [~s]~n', [req])
    :timer.sleep(1000)
    :ok = :erlzmq.send(socket, "World")
    loop(socket)
  end

end

Rrworker.main()
