defmodule Version do
  @moduledoc """
  Generated by erl2ex (http://github.com/dazuma/erl2ex)
  From Erlang source: (Unknown source file)
  At: 2019-12-20 13:57:38

  """

  def main() do
    {maj, var_min, patch} = :erlzmq.version()
    :io.format('Current 0MQ version is ~b.~b.~b~n', [maj, var_min, patch])
  end

end

Version.main
