defmodule Wuproxy do
  @moduledoc """
  Generated by erl2ex (http://github.com/dazuma/erl2ex)
  From Erlang source: (Unknown source file)
  At: 2019-12-20 13:57:39

  """

  def main(_) do
    {:ok, context} = :erlzmq.context()
    {:ok, frontend} = :erlzmq.socket(context, :sub)
    :ok = :erlzmq.connect(frontend, 'tcp://localhost:5556')
    {:ok, backend} = :erlzmq.socket(context, :pub)
    :ok = :erlzmq.bind(backend, 'tcp://*:8100')
    :ok = :erlzmq.setsockopt(frontend, :subscribe, <<>>)
    loop(frontend, backend)
    :ok = :erlzmq.close(frontend)
    :ok = :erlzmq.close(backend)
    :ok = :erlzmq.term(context)
  end


  def loop(frontend, backend) do
    {:ok, msg} = :erlzmq.recv(frontend)
    case(:erlzmq.getsockopt(frontend, :rcvmore)) do
      {:ok, true} ->
        :erlzmq.send(backend, msg, [:sndmore])
      {:ok, false} ->
        :erlzmq.send(backend, msg)
      {:ok, 0} ->
        :erlzmq.send(backend, msg)
    end
    loop(frontend, backend)
  end

end

Wuproxy.main(:ok)
