defmodule Wuserver do
  @moduledoc """
  Generated by erl2ex (http://github.com/dazuma/erl2ex)
  From Erlang source: (Unknown source file)
  At: 2019-12-20 13:57:40

  """

  def main(_) do
    {:ok, context} = :erlzmq.context()
    {:ok, publisher} = :erlzmq.socket(context, :pub)
    :ok = :erlzmq.bind(publisher, 'tcp://*:5556')
    loop(publisher)
    :ok = :erlzmq.close(publisher)
    :ok = :erlzmq.term(context)
  end


  def loop(publisher) do
    zipcode = :random.uniform(100000)
    temperature = :random.uniform(215) - 80
    relhumidity = :random.uniform(50) + 10
    msg = :erlang.list_to_binary(:io_lib.format('~5..0b ~b ~b', [zipcode, temperature, relhumidity]))
    :ok = :erlzmq.send(publisher, msg)
    loop(publisher)
  end

end

Wuserver.main(:ok)
