#! /bin/sh
#
#   Examples build helper
#   Syntax: build all | clean
#
if [ /$1/ = /all/ ]; then
    echo "Building C examples..."
    for MAIN in `egrep -l main *.c`; do
        echo "$MAIN"
        ./c -l -lzmq -q $MAIN
    done
elif [ /$1/ = /clean/ ]; then
    echo "Cleaning C examples directory..."
    rm -f *.o *.lst core
    for MAIN in `egrep -l main *.c`; do
        rm -f `basename $MAIN .c`
    done
elif [ -f $1.c ]; then
    echo "$1"
    ./c -l -lzmq -q $1
else
    echo "syntax: build all | clean"
fi
