#! /bin/sh
#
#   Examples build helper
#   Syntax: build all | clean
#
if [ /$1/ = /all/ ]; then
    echo "Building C examples..."
    for MAIN in *.c; do
        echo "$MAIN"
        ./c -l -lzmq -q $MAIN
    done
elif [ /$1/ = /clean/ ]; then
    echo "Cleaning C examples directory..."
    rm -f *.o *.lst core
    for MAIN in *.c; do
        rm `basename $MAIN .c`
    done
else
    echo "syntax: build all | clean"
fi

