#! /bin/sh
#
#   Examples build helper
#   Syntax: build all | clean
#
MAINS="hwclient hwserver mtserver wuserver wuclient wuproxy taskvent"
MAINS="$MAINS taskwork tasksink msreader mspoller taskwork2 tasksink2"
MAINS="$MAINS rrbroker msgqueue"
MJSON="device"

if [ /$1/ = /all/ ]; then
    echo "Building C examples..."
    for MAIN in $MAINS; do
        echo -n "$MAIN "
        gcc -g -DDEBUG -O2 -Wall -lzmq $MAIN.c -o $MAIN
    done
    for MAIN in $MJSON; do
        echo -n "$MAIN "
        gcc -g -DDEBUG -O2 -Wall -lzmq $MAIN.c cJSON.c -o $MAIN
    done
    echo "Done"
elif [ /$1/ = /clean/ ]; then
    echo "Cleaning C examples directory..."
    rm -f *.o *.lst core $MAINS $MJSON
elif [ -f $1.c ]; then
    gcc -g -DDEBUG -O2 -Wall -lzmq $1.c cJSON.c -o $1
else
    echo "syntax: build all | clean"
fi
