#! /bin/sh
#
#   Examples build helper
#   Syntax: build all | clean
#
MAIN="hwclient hwserver mtserver"
if [ /$1/ = /all/ ]; then
    echo "Building C++ examples..."
    ./c -p -l -lzmq -q $MAIN
elif [ /$1/ = /clean/ ]; then
    echo "Cleaning C++ examples directory..."
    rm -f *.opp *.lst core $MAIN
else
    echo "syntax: build all | clean"
fi


