#! /bin/sh
#
#   Examples build helper
#   Syntax: build all | clean
#
#   Note: may fail with g++/4.0.x, then
#   build examples using 'g++ -o filename -lzmq filename.cpp'
#
if [ /$1/ = /all/ ]; then
    echo "Building C++ examples..."
    for MAIN in `egrep -l "main \(" *.cpp`; do
        echo "$MAIN"
        ./c -p -l -lzmq -q $MAIN
    done
elif [ /$1/ = /clean/ ]; then
    echo "Cleaning C++ examples directory..."
    rm -f *.opp *.lst core
    for MAIN in `egrep -l "main \(" *.cpp`; do
        rm -f `basename $MAIN .cpp`
    done
elif [ -f $1.cpp ]; then
    echo "$1"
    ./c -p -l -lzmq -q $1
else
    echo "syntax: build all | clean"
fi

