#! /bin/sh
#
#   Examples build helper
#   Syntax: build all | clean
#
#   requires $GOARCH env variable (amd64 or i386)
#   to determine using 6g or 8g compiler
#
if [ /$1/ = /all/ ]; then
    echo "Building Go examples..."
    echo "Current GOARCH = $GOARCH"

    for MAIN in `ls *.go | sed 's/.go//g'`; do
        echo "$MAIN"
        rm -f $MAIN
        if [ /$GOARCH/ = /amd64/ ]; then
          6g $MAIN.go && 6l -o $MAIN $MAIN.6 
        else
          8g $MAIN.go && 8l -o $MAIN $MAIN.8 
        fi
    done
    rm -f *.6 *.8
elif [ /$1/ = /clean/ ]; then
    echo "Cleaning C++ examples directory..."
    rm -f *.6
    for MAIN in `ls *.go | 's/.go//g'`; do
        rm -f $MAIN
    done
elif [ -f $1.cpp ]; then
    echo "$1"
    if [ /$GOARCH/ = /amd64/ ]; then
      6g $MAIN.go && 6l -o $MAIN $MAIN.6 
    else
      8g $MAIN.go && 8l -o $MAIN $MAIN.8 
    fi
    rm -f $MAIN.6 $MAIN.8
else
    echo "syntax: build all | clean"
fi

